name: Node.js CI

on:
  pull_request:
    branches:
      - development
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_KEY: teste
      EXPIRES_IN: 1h

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "yarn"

      - name: Install dependencies
        run: yarn

      - name: Build
        run: yarn run build

      - name: Test
        run: yarn test --coverage
